project_id = "uszlfqgxjvceugrpavde"

[functions.run-scraper]
verify_jwt = false

[functions.daily-scrape]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.send-email]
verify_jwt = false